#functions to create and write out dataframes compatible with the Arlequin data format
#requires a dataframe with each individuals genotyped locus side by side
#write_arlq is a modified function of radiator::write_arlequin() created by Thierry Gosselin. 
#Pedro Senna Bittencourt November 2020

#requires dplyr and magrittr
library(tidyverse)
library(magrittr)


# fun to convert dataframes
df2arlq <- function(data){
  if(missing(data)){
    stop("Input file is missing")
  }
pair <- data %>% select(-Individuals, -Population) %>% 
  select(which(seq_along(.) %% 2 == 0)) %>% mutate(tbl = "2")
colnames(pair) <- lapply(colnames(pair), function(x) strsplit(x, split = ".", fixed = TRUE)) %>% sapply(function(x) paste(x[[1]][1]))
odd <- data %>% select(-Individuals, -Population) %>% 
  select(which(seq_along(.) %% 2 == 1)) %>% mutate(tbl = "1")
colnames(odd) <- lapply(colnames(odd), function(x) strsplit(x, split = ".", fixed = TRUE)) %>% sapply(function(x) paste(x[[1]][1]))
df1 <- odd %>% mutate(row_number = row_number()) %>%
  bind_rows(pair %>% mutate(row_number = row_number())) %>% arrange(row_number, tbl)  
data %<>% mutate(row_number = row_number()) %>% select(Individuals, Population, row_number)
df2 <- merge(data, df1, by = "row_number") %>% select(-row_number, -tbl)
return(df2)
}

# fun to write out files
write_arlq <- function(data, filename){
  
filename.connection <- file(filename, "w")
write("[Profile]", file = filename.connection)
write(paste("Title =", "\"Generated by df2arlq.R\""), file = filename.connection, append = TRUE)
write(paste("NbSamples = ", length(unique(data$Population))), file = filename.connection, 
      append = TRUE)
write(paste("GenotypicData = 1"), file = filename.connection, 
      append = TRUE)
write(paste("LocusSeparator = TAB"), file = filename.connection, 
      append = TRUE)
write(paste("GameticPhase = 0"), file = filename.connection, 
      append = TRUE)
write(paste("MissingData = '?'"), file = filename.connection, 
      append = TRUE)
write(paste("DataType = STANDARD"), file = filename.connection, 
      append = TRUE)
write(paste("[Data]"), file = filename.connection, append = TRUE)
write(paste("[[Samples]]"), file = filename.connection, 
      append = TRUE)
data.split <- data %>% group_split(by=Population)
for (i in 1:length(data.split)) {
  pop.data <- data.split[[i]]
  pop.name <- paste0("\"",unique(data.split[[i]]$Population),"\"")
  n.ind <- dplyr::n_distinct(pop.data$Individuals)
  write(paste("SampleName = ", pop.name), file = filename.connection, 
        append = TRUE)
  write(paste("SampleSize = ", n.ind), file = filename.connection, 
        append = TRUE)
  write(paste("SampleData = {"), file = filename.connection, 
        append = TRUE)
  pop.data %<>% mutate(Population = "1") %<>% mutate_at(vars(Individuals:Population), ~replace(., which(seq_along(.) %% 2== 0), "")) %>% select(-by)
  write(x = t(pop.data), ncolumns = ncol(pop.data), sep = "\t", append = TRUE, file = filename.connection)
  write("}", file = filename.connection, append = TRUE)
}
  write(paste("[[Structure]]"), file = filename.connection, 
        append = TRUE)
  write(paste("StructureName = ", "\"One Cluster\""), 
        file = filename.connection, append = TRUE)
  write(paste("NbGroups = 1"), file = filename.connection, 
        append = TRUE)
  write(paste("Group = {"), file = filename.connection, append = TRUE)
  for (i in 1:length(data.split)) {
    pop.data <- data.split[[i]]
    pop.name <- unique(data.split[[i]]$Population)
    write(paste("\"", pop.name, "\"", sep = ""), file = filename.connection, 
          append = TRUE)
  }
  write(paste("}"), file = filename.connection, append = TRUE)
  invisible(data)
  close(filename.connection)
}


#examples
#data <- data.frame(Individuals= c("sample 01", "sample 02", "sample 03"), 
         #Population = c(1,2,3), Locus1.1 = c(1,2,3), Locus1.2 =c(4,5,6), 
         #Locus2.1 = c(7,8,9), Locus2.2 =c(10,11,12))

#df <- df2arlq(data)

#write_arlq(df, filename = "data.arp")
